export interface DeliveryZoneSeed {
  code: string
  name: string
  aliases: string[]
  roundTripMinutes: number
  deliveryFee: number
  sortOrder: number
}

export const DELIVERY_ZONE_SEEDS: DeliveryZoneSeed[] = [
  {
    code: 'ivatevichi',
    name: 'Ивацевичи',
    aliases: ['ивцевичи', 'город'],
    roundTripMinutes: 5,
    deliveryFee: 0,
    sortOrder: 0,
  },
  {
    code: 'mihnovichi',
    name: 'Михновичи',
    aliases: ['михновичи'],
    roundTripMinutes: 10,
    deliveryFee: 0,
    sortOrder: 10,
  },
  {
    code: 'panki',
    name: 'Панки',
    aliases: ['панки'],
    roundTripMinutes: 15,
    deliveryFee: 0,
    sortOrder: 20,
  },
  {
    code: 'kholopya',
    name: 'Холопья',
    aliases: ['холопья'],
    roundTripMinutes: 10,
    deliveryFee: 0,
    sortOrder: 30,
  },
  {
    code: 'ozerco',
    name: 'Озерцо',
    aliases: ['озерцо'],
    roundTripMinutes: 15,
    deliveryFee: 5,
    sortOrder: 40,
  },
  {
    code: 'ozero2',
    name: '2-е озеро',
    aliases: ['2 е озеро', '2-е озеро', '2e ozero', 'второе озеро'],
    roundTripMinutes: 20,
    deliveryFee: 10,
    sortOrder: 50,
  },
  {
    code: 'maisk',
    name: 'Майск',
    aliases: ['майск'],
    roundTripMinutes: 25,
    deliveryFee: 5,
    sortOrder: 60,
  },
  {
    code: 'yaglevichi',
    name: 'Яглевичи',
    aliases: ['яглевичи'],
    roundTripMinutes: 20,
    deliveryFee: 5,
    sortOrder: 70,
  },
  {
    code: 'podstarin',
    name: 'Подстаринь',
    aliases: ['подстаринь'],
    roundTripMinutes: 20,
    deliveryFee: 5,
    sortOrder: 80,
  },
  {
    code: 'pyatak',
    name: 'Пятак',
    aliases: ['пятак'],
    roundTripMinutes: 15,
    deliveryFee: 5,
    sortOrder: 90,
  },
  {
    code: 'volya',
    name: 'Воля',
    aliases: ['воля'],
    roundTripMinutes: 15,
    deliveryFee: 5,
    sortOrder: 100,
  },
  {
    code: 'barany',
    name: 'Бараны',
    aliases: ['бараны'],
    roundTripMinutes: 15,
    deliveryFee: 0,
    sortOrder: 110,
  },
  {
    code: 'goschevo',
    name: 'Гощево',
    aliases: ['гощево'],
    roundTripMinutes: 20,
    deliveryFee: 7,
    sortOrder: 120,
  },
  {
    code: 'stayki',
    name: 'Стайки',
    aliases: ['стайки'],
    roundTripMinutes: 20,
    deliveryFee: 0,
    sortOrder: 130,
  },
  {
    code: 'alexeyki',
    name: 'Алексейки',
    aliases: ['алексейки'],
    roundTripMinutes: 20,
    deliveryFee: 5,
    sortOrder: 140,
  },
  {
    code: 'lyubishchitsy',
    name: 'Любищицы',
    aliases: ['любищицы'],
    roundTripMinutes: 20,
    deliveryFee: 5,
    sortOrder: 150,
  },
  {
    code: 'zeleny_bor',
    name: 'Зелёный Бор',
    aliases: ['зеленый бор', 'зелёный бор'],
    roundTripMinutes: 35,
    deliveryFee: 15,
    sortOrder: 160,
  },
  {
    code: 'nekhachevo',
    name: 'Нехачево',
    aliases: ['нехачево'],
    roundTripMinutes: 25,
    deliveryFee: 15,
    sortOrder: 170,
  },
  {
    code: 'kossovo',
    name: 'Коссово',
    aliases: ['коссово'],
    roundTripMinutes: 30,
    deliveryFee: 15,
    sortOrder: 180,
  },
  {
    code: 'busyazh',
    name: 'Бусяж',
    aliases: ['бусяж'],
    roundTripMinutes: 45,
    deliveryFee: 20,
    sortOrder: 190,
  },
  {
    code: 'galenchitsy',
    name: 'Галенчицы',
    aliases: ['галенчицы'],
    roundTripMinutes: 20,
    deliveryFee: 10,
    sortOrder: 200,
  },
  {
    code: 'mileyki',
    name: 'Милейки',
    aliases: ['милейки'],
    roundTripMinutes: 30,
    deliveryFee: 15,
    sortOrder: 210,
  },
  {
    code: 'zapolye',
    name: 'Заполье',
    aliases: ['заполье'],
    roundTripMinutes: 40,
    deliveryFee: 15,
    sortOrder: 220,
  },
]
